### PR TITLE
sasl_saml authentication

### LINKED ISSUE #153: SASL_SSL / SCRAM support
Hi, 

as far as I understand SASL_SSL is not supported (and consequently SCRAM-SHA-512 is not supported too) any plans for this or eventually a hint where should I start to hack?

### PR DESCRIPTION
**Pull request by krisek**
Fixes #153

### CODE REVIEW

**Comment by hackaugusto** [comment]
Hey @krisek , thank you very much for the contribution. I wonder if you could add some tests for this feature?

**Comment by krisek** [comment]
> I wonder if you could add some tests for this feature?

Of course, when it is about extending existing tests --- is there a developer guide?

**Comment by hackaugusto** [comment]
Hey @krisek , I didn't forget about your question. I'm working on making testing easier/faster with [parallelization](https://github.com/aiven/karapace/pull/161) and I want to introduce tox for multi target local tests. This would conflict with the changes to test SASL. To save you the hassle of fixing the conflicts I delayed the reply a bit, I hope you don't mind.

Unfortunately there is not contributing guide yet, it is on my todo list. The short setup is roughly this:

```sh
python3.7 -m venv <path_to_your_venv>
source <path_to_your_venv>/bin/activated
cd <karapace_checkout>
pip install -r requirements-dev.txt
pip install -e .
make fetch-kafka
# now you can run tests with pytest tests/unit or pytest tests/integration
```

To test your changes we need to configure the [kafka servers executed for the tests](https://github.com/aiven/karapace/blob/2856c7d660c6fb554dbe99d5430fe0738dc06cbc/tests/integration/conftest.py#L413-L442) to support [SASL](https://kafka.apache.org/documentation/#security_jaas_broker)

**Review by hackaugusto — APPROVED** [review]

**Comment by hackaugusto** [comment]
@krisek thank you for the pr, sorry for the delay in merging it

**Pull request merged**
