### PR TITLE
Update kafka-python and fix api change.

### PR DESCRIPTION
**Pull request by hackaugusto**
`git+git://github.com/aiven/kafka-python.git@346c01e4eec6bdcccc99ca613b79020f3be35eb7` ~is the current commit for https://github.com/aiven/kafka-python/tree/aiven_patches , which is rebased on top of dpkp's master.~ `master` was updated instead, it is the same commit but now master points to it.

During the review fo https://github.com/dpkp/kafka-python/pull/2144 the configuration key changed name.

### CODE REVIEW

**Comment by mts-aiven** [comment]
Maybe add note about kafka-python to commit message also. Otherwise, LGTM.

**Comment by hackaugusto** [comment]
> Maybe add note about kafka-python to commit message also. Otherwise, LGTM.

I don't follow, the link to the upstream PR?

**Comment by mts-aiven** [comment]
> > Maybe add note about kafka-python to commit message also. Otherwise, LGTM.
> 
> I don't follow, the link to the upstream PR?

Just the commit in this pull, that it updates the requirements-dev.txt

**Comment by hackaugusto** [comment]
@mts-aiven updated the commit message

**Review by mts-aiven — APPROVED** [review]
LGTM

**Pull request merged**
