### PR TITLE
References for protobuf serialization/deserialization (DEPRECATED)

### PR DESCRIPTION
**Pull request by libretto**
Add support of references to serialization/deserialization protobuf functionality

### CODE REVIEW

**Comment by mdedetrich** [comment]
@libretto I will try and have a look at this, are the test failures expected or is it an external cause?

**Comment by libretto** [comment]
Locally all test was passed successfully. Lint failure is related to some issues in karapace gitlab usage. 
But Test suite failure is strange. Does it happen on the first run of tests?

**Comment by mdedetrich** [comment]
> Does it happen on the first run of tests?

I am not that familiar with this project specifically which is why I was asking

**Comment by libretto** [comment]
@mdedetrich  Could You re-run the workflow?

**Pull request closed without merging**
