### PR TITLE
website: Add Sphinx website with a base for docs

### PR DESCRIPTION
**Pull request by blomqma**
This adds additional changes to the initial
website reboot changes that introduced Sphinx
for the docs part. The landing page is finished
here to make it look more or less exact same as
in the Figma desings.

The styling for the actual docs content is quite
minimal with the basic setup that comes from the
Furo theme and a few additional color variables,
logos etc.

The landing page is styled with TailwindCSS and
it can be used to style other custom templates
as well.

### CODE REVIEW

**Comment by blomqma** [comment]
Screenshot 2022-11-11 at 15 31 24

Screenshot 2022-11-11 at 15 31 46

Screenshot 2022-11-11 at 15 31 56

Screenshot 2022-11-11 at 15 32 29

Screenshot 2022-11-11 at 15 32 40

**Comment by blomqma** [comment]
> Is there a preview link (like we have for Console) so I can check it before we deploy it? :) Thanks...

Replied elsewhere, but we have a deployment setup that we can use to deploy this internally as soon as the initial version of this new website is merged to main and iterate from there on.

**Comment by lornajane** [comment]
Cool! How do I run this locally? I installed requirements for both python and node, found a tailwind build script to run but still the generated HTML doesn't look correct for the front page - the inner pages are nice though! Let's figure out what I missed and put it in the `README` for the next person that can't figure it out?

**Comment by blomqma** [comment]
> Cool! How do I run this locally? I installed requirements for both python and node, found a tailwind build script to run but still the generated HTML doesn't look correct for the front page - the inner pages are nice though! Let's figure out what I missed and put it in the `README` for the next person that can't figure it out?

I added some documentation in the `README` of the website, but basically the styles should work with a combination of `make tailwind-build`/`make tailwind-watch` and `make html`/`make livehtml`/`make livehtmlall`.

**Review by lornajane — COMMENTED** [review]
This looks really good! The community link doesn't seem to go anywhere - is that going to the GitHub page, or should I add a page to the docs for that to point to?

Can we somehow indicate that the website itself is also on GitHub? (the docs site uses the github ribbon, but I don't mind if we solve this a different way)

**Comment by blomqma** [comment]
> This looks really good! The community link doesn't seem to go anywhere - is that going to the GitHub page, or should I add a page to the docs for that to point to?
> 
> Can we somehow indicate that the website itself is also on GitHub? (the docs site uses the github ribbon, but I don't mind if we solve this a different way)

Yeah I added a TODO comment for the community link that is currently dead as I also had no idea where that should lead but a separate page on the website sounds good. A GitHub ribbon that leads to GitHub for the website development also sounds good to me and I could add that here.

**Comment by blomqma** [comment]
@lornajane I added one more commit with a similar GH ribbon for the docs that we have in the devportal docs.

**Comment by blomqma** [comment]
Looks like the CI is failing with the following error, no idea what's that about:
```
fatal: could not read Username for 'https://gitlab.com/': No such device or address
```

**Review by vtainio — CHANGES_REQUESTED** [review]
Looks great to me! We need to a few things like favicon etc. but I think it's easier to do those after this PR is merged. Just needs the rebase to get the CI working.

**Comment by blomqma** [comment]
Rebased on main, changed the base branch also to main. Do you think I should squash some of the earlier commits together?

**Comment by vtainio** [comment]
@blomqma I think that would be the best and we could prefix the commit message with `website: `

**Review by vtainio — APPROVED** [review]

**Pull request merged**
